### ISSUE TITLE
Write a dataset_check.py

### ISSUE THREAD

**Issue by ameintjes** [h3abionet/african_genomics_medicine_portal#24]
This should be a standalone script thatchecks the dummy_data files for issues such as:

- duplicated drug_id, gene_id etc

**Comment by codemeleon** [comment]
I think we should use pandas read_csv/read_table, instead of using csv reader. This will help to avoid column order related issues if we fix the names of columns.

**Comment by codemeleon** [comment]
I have  pushed the code for drug_id, gene_id  duplication testing. However, I might need make some new modifications based merges.

**Comment by codemeleon** [comment]
Done. Closing this issue. Please let me know any other action required.
